coverage:
  range: 60..100
  round: down
  precision: 2
  status:
    patch:
      default:
        target: 60%
        threshold: 5%
    project:
      default:
        target: 80%
        threshold: 5%
