[versions]
# libraries
elasticsearch = "8.11.1"
velocity = "2.3"
junit = "5.10.1"
hamcrest = "2.2"
log4j = "2.21.1"

# plugins


[libraries]
elasticsearch = { module = "org.elasticsearch:elasticsearch", version.ref = "elasticsearch" }
velocity = { module = "org.apache.velocity:velocity-engine-core", version.ref = "velocity" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
hamcrest = { module = "org.hamcrest:hamcrest", version.ref = "hamcrest" }
log4j = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }

[plugins]



