name: Codecov
on:
  push:
    paths-ignore:
      - "README.md"
      - "README.zh-CN.md"
  pull_request:
    paths-ignore:
      - "README.md"
      - "README.zh-CN.md"
jobs:
  codecov:
    name: Codecov
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@master

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build Code Coverage Report
        run: ./gradlew jacocoTestReport --stacktrace

      - name: Upload Code Coverage Report to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
          files: ./build/reports/jacoco/test/jacocoTestReport.xml
          path_to_write_report: ./coverage/codecov_report.txt
